package rest

import (
	"log"
	"net/smtp"
	"time"
)

func (b *BimsConfiguration) SendPasswordViaEmail(to string, fullname string, username string, password string) error {

	currentTime := time.Now()
	dateString := currentTime.Format("2006-01-02 03:04 PM")

	msg := "From: " + b.from + "\n" +
		"To: " + to + "\n" +
		"Subject: Autogenerated BIMS: Credentials Email - " + dateString + "\n\n" +
		"Dear " + fullname + ", \n\n\n" +
		"Here's your BIMS Account Credentials. Please login and change password as soon as possible.\n\n" +
		"Username: " + username + "\n" +
		"Password: " + password + "\n\n\n" +
		"If you have any concerns please contact you administrator!\n\n" +
		"Regards,\n" +
		"Bims Autogenerated Email"

	err := smtp.SendMail("smtp.gmail.com:587",
		smtp.PlainAuth("", b.from, b.pass, "smtp.gmail.com"),
		b.from, []string{to}, []byte(msg))

	if err != nil {
		return err
	}

	log.Print("Email Sent!")
	return nil
}
